# Definition of cosmological functions

In [1]:
import numpy as np
from scipy.integrate import quad as intquad # To integrate
from scipy.interpolate import interp1d # To interpolate the integral in the luminosity distance

NOTES


## General fixed values

In [21]:
c = 299792.458  # Speed of light
# OmRFix =0.000085 # Radiation component today

aFactor = 10

# Inverse of Dimensionless Hubble parameter

### Omega function

In [5]:
# np.exp(10)

In [6]:
# NEW
# definition of w=e^(5*a)

def Omega(OmL, OmM, a):
    "Definition of Omega bold as given by Norman"
    OmegaInt = OmL*6*(np.exp(aFactor*a)+1)/(3*np.exp(aFactor*a)+4) + OmM*(2*np.exp(aFactor*a)+3)/(2*np.exp(aFactor*a)+4) - 3*(1+np.exp(aFactor*a))/np.exp(aFactor*a) + np.sqrt(9/np.exp(aFactor*a)**2 - 6*(OmL + OmM*(2*np.exp(aFactor*a)+3)/(2*np.exp(aFactor*a)+4) - 1)/np.exp(aFactor*a))   
    return OmegaInt

# Omega(0.99, 0.01, 1)
# -1.0112293704199862

-1.0144074760990267

In [129]:
# Previous 1
# definition of w=e^a
'''
def Omega(OmL, OmM, a):
    "Definition of Omega bold as given by Norman"
    OmegaInt = OmL*6*(np.exp(a)+1)/(3*np.exp(a)+4) + OmM*(2*np.exp(a)+3)/(2*np.exp(a)+4) - 3*(1+np.exp(a))/np.exp(a) + np.sqrt(9/np.exp(a)**2 - 6*(OmL + OmM*(2*np.exp(a)+3)/(2*np.exp(a)+4) - 1)/np.exp(a))      
    return OmegaInt

# Omega(0.99, 0.01, 8)
# -1.0112293704199862
'''
0

-1.0102213077413036

In [120]:
# Original definition of w
'''
def Omega(OmL, OmM, w):
    "Definition of Omega bold as given by Norman"
    OmegaInt = OmL*6*(w+1)/(3*w+4) + OmM*(2*w+3)/(2*w+4) - 3*(1+w)/w 
    + np.sqrt(9/w**2 - 6*(OmL + OmM*(2*w+3)/(2*w+4) - 1)/w)
    return OmegaInt

# Omega(0.99, 0.01, 3000)
# -1.0102215678219557

'''
0

-1.0102215678219557

### Inverse dimensionless Hubble parameter

In [110]:
# Redshift
def InvEHubble_Simple(z, OmL, OmM, a):
    "Dimensionless Hubble parameter"
    # InvEHubbleSimpleInt = 1.0/np.sqrt((1.+z)**((3.*np.exp(a)+4.)/(np.exp(a)+1.))*(1. - Omega(OmL, OmM, a))
    #                                   + Omega(OmL, OmM, a))
    
    InvEHubbleSimpleInt = 1.0/((1.+z)**((3.*np.exp(aFactor*a)+4.)/(np.exp(aFactor*a)+1.))*(1. - Omega(OmL, OmM, a))
                                      + Omega(OmL, OmM, a))
                                  
    return InvEHubbleSimpleInt

# Checking output
# InvEHubble_Simple(1, 0.7, 0.3, 1000)
# 0.24170488257679618

In [112]:
# InvEHubble_Simple(0.2, 0.99, 0.01, 8)
# 0.24170488257679618

0.40578034428331494

## Luminosity distance $d_L$

In [113]:
# Luminosity distance
def LumDist_Simple(z, OmL, OmM, a, Ho):
    "Luminosity distance"
    
    LumDistSimpleInt = 0.
    LumDistSimpleInt = c*(1.+z)*intquad(InvEHubble_Simple, 0., z, args=(OmL, OmM, a))[0]/Ho
        
    return LumDistSimpleInt

# LumDist_Simple(1, 0.7, 0.3, 1000, 70.)
# 3881.5276900078775

-----

# Scratch

In [4]:
# """
Par1_initial = 1
Par2_initial = 0.00001
Par3_initial = 4
result = np.array([Par1_initial, Par2_initial, Par3_initial])

result

# """ 


array([  1.00000000e+00,   1.00000000e-05,   4.00000000e+00])

In [5]:

# """ 
ndim, nwalkers = 3, 10
pos = [result + 1e-3*np.random.randn(ndim) for i in range(nwalkers)]
pos

# """ 

[array([  9.98764683e-01,   1.05848973e-03,   3.99873217e+00]),
 array([  1.00137329e+00,  -4.69046144e-04,   3.99957325e+00]),
 array([  1.00158601e+00,  -8.46004429e-04,   4.00203245e+00]),
 array([  1.00040291e+00,   2.97547166e-03,   3.99856066e+00]),
 array([  1.00154807e+00,   1.09172963e-04,   4.00048760e+00]),
 array([  9.99178936e-01,   1.92086950e-05,   4.00075227e+00]),
 array([  1.00053768e+00,   3.74227432e-05,   3.99849791e+00]),
 array([  9.99514249e-01,   3.12787958e-04,   3.99959681e+00]),
 array([  1.00047717e+00,  -1.07927286e-03,   4.00100766e+00]),
 array([  9.98770459e-01,   2.99141773e-04,   4.00110780e+00])]

In [6]:
np.random.randn(3)

array([-0.30599242,  1.45503497, -0.63204996])

In [7]:
np.random.randn(1)

array([-0.14121559])

In [9]:
np.random.randn()

-0.037946203302111056

In [10]:
np.random.random_sample(1)

array([ 0.10568124])

In [11]:
np.random.random_sample()

0.727271087564396

In [ ]:
ndim, nwalkers = 3, 10
pos = [result[0] + 1e-3*np.random.randn(1) for i in range(nwalkers)]
pos

In [24]:
# """ 
pos = []
factorInitialChain = 1e-3

for i in range(nwalkers):
    pos += [np.array([ result[0] - factorInitialChain*np.random.random_sample(),
            result[1] + factorInitialChain*np.random.random_sample(),
            result[2] + factorInitialChain*np.random.randn() ]) ]
    
# """ 

In [25]:
pos

[array([  9.99309193e-01,  -8.28692486e-04,   4.00022227e+00]),
 array([  9.99431164e-01,  -3.63397822e-04,   4.00008051e+00]),
 array([  9.99400273e-01,  -8.97684045e-04,   3.99908091e+00]),
 array([  9.99730292e-01,  -7.82050603e-04,   3.99884247e+00]),
 array([  9.99974529e-01,  -3.99452508e-04,   4.00054488e+00]),
 array([  9.99857982e-01,  -6.85119267e-04,   3.99982782e+00]),
 array([  9.99885259e-01,  -8.57329528e-04,   3.99889070e+00]),
 array([  9.99100228e-01,  -5.83318826e-04,   3.99920305e+00]),
 array([  9.99186878e-01,  -2.39392495e-04,   4.00248321e+00]),
 array([  9.99078986e-01,  -1.66481402e-04,   3.99946599e+00])]

In [14]:
np.array([1,2,3])

array([1, 2, 3])