# Definition of cosmological functions

In [3]:
import numpy as np
from scipy.integrate import quad as intquad # To integrate
from scipy.interpolate import interp1d # To interpolate the integral in the luminosity distance

NOTES


## General fixed values

In [8]:
c = 299792.458  # Speed of light
# OmRFix =0.000085 # Radiation component today

aFactor = 8

# Inverse of Dimensionless Hubble parameter

### Omega function

In [5]:
# np.exp(10)

In [6]:
# NEW
# definition of w=e^(5*a)

def Omega(OmL, OmM, a):
    "Definition of Omega bold as given by Norman"
    OmegaInt = OmL*6*(np.exp(aFactor*a)+1)/(3*np.exp(aFactor*a)+4) + OmM*(2*np.exp(aFactor*a)+3)/(2*np.exp(aFactor*a)+4) - 3*(1+np.exp(aFactor*a))/np.exp(aFactor*a) + np.sqrt(9/np.exp(aFactor*a)**2 - 6*(OmL + OmM*(2*np.exp(aFactor*a)+3)/(2*np.exp(aFactor*a)+4) - 1)/np.exp(aFactor*a))   
    return OmegaInt

# Omega(0.99, 0.01, 1)
# -1.0112293704199862

-1.0144074760990267

In [129]:
# Previous 1
# definition of w=e^a
'''
def Omega(OmL, OmM, a):
    "Definition of Omega bold as given by Norman"
    OmegaInt = OmL*6*(np.exp(a)+1)/(3*np.exp(a)+4) + OmM*(2*np.exp(a)+3)/(2*np.exp(a)+4) - 3*(1+np.exp(a))/np.exp(a) + np.sqrt(9/np.exp(a)**2 - 6*(OmL + OmM*(2*np.exp(a)+3)/(2*np.exp(a)+4) - 1)/np.exp(a))      
    return OmegaInt

# Omega(0.99, 0.01, 8)
# -1.0112293704199862
'''
0

-1.0102213077413036

In [120]:
# Original definition of w
'''
def Omega(OmL, OmM, w):
    "Definition of Omega bold as given by Norman"
    OmegaInt = OmL*6*(w+1)/(3*w+4) + OmM*(2*w+3)/(2*w+4) - 3*(1+w)/w 
    + np.sqrt(9/w**2 - 6*(OmL + OmM*(2*w+3)/(2*w+4) - 1)/w)
    return OmegaInt

# Omega(0.99, 0.01, 3000)
# -1.0102215678219557

'''
0

-1.0102215678219557

### Inverse dimensionless Hubble parameter

In [110]:
# Redshift
def InvEHubble_Simple(z, OmL, OmM, a):
    "Dimensionless Hubble parameter"
    # InvEHubbleSimpleInt = 1.0/np.sqrt((1.+z)**((3.*np.exp(a)+4.)/(np.exp(a)+1.))*(1. - Omega(OmL, OmM, a))
    #                                   + Omega(OmL, OmM, a))
    
    InvEHubbleSimpleInt = 1.0/((1.+z)**((3.*np.exp(aFactor*a)+4.)/(np.exp(aFactor*a)+1.))*(1. - Omega(OmL, OmM, a))
                                      + Omega(OmL, OmM, a))
                                  
    return InvEHubbleSimpleInt

# Checking output
# InvEHubble_Simple(1, 0.7, 0.3, 1000)
# 0.24170488257679618

In [112]:
# InvEHubble_Simple(0.2, 0.99, 0.01, 8)
# 0.24170488257679618

0.40578034428331494

## Luminosity distance $d_L$

In [113]:
# Luminosity distance
def LumDist_Simple(z, OmL, OmM, a, Ho):
    "Luminosity distance"
    
    LumDistSimpleInt = 0.
    LumDistSimpleInt = c*(1.+z)*intquad(InvEHubble_Simple, 0., z, args=(OmL, OmM, a))[0]/Ho
        
    return LumDistSimpleInt

# LumDist_Simple(1, 0.7, 0.3, 1000, 70.)
# 3881.5276900078775

-----

# Scratch

In [4]:

Par1_initial = 1
Par2_initial = 0.00001
Par3_initial = 4
result = np.array([Par1_initial, Par2_initial, Par3_initial])


In [5]:
# result

array([  1.00000000e+00,   1.00000000e-05,   4.00000000e+00])

In [7]:

ndim, nwalkers = 3, 10
pos = [result + 1e-3*np.random.randn(ndim) for i in range(nwalkers)]
pos


[array([  1.00074026e+00,  -5.57340992e-04,   4.00084464e+00]),
 array([  1.00006213e+00,   2.82561867e-04,   4.00015189e+00]),
 array([  1.00161403e+00,   8.90932599e-04,   4.00023244e+00]),
 array([  1.00011526e+00,   1.40197835e-03,   4.00123796e+00]),
 array([  9.99060930e-01,   1.33333016e-03,   4.00146919e+00]),
 array([  1.00076443e+00,  -8.15900264e-05,   3.99966608e+00]),
 array([  9.98844140e-01,  -1.32983607e-03,   4.00004365e+00]),
 array([  1.00095878e+00,   2.12747755e-04,   3.99941628e+00]),
 array([  9.98371733e-01,   2.47229469e-04,   4.00083726e+00]),
 array([  9.99865796e-01,  -1.02597899e-03,   3.99860523e+00])]

In [9]:
np.random.randn(3)

array([-0.79547446, -0.78610492,  0.14368176])

In [18]:
np.random.randn()

-0.3558900241311909

In [13]:
np.random.random_sample()

0.9321411755765278

In [ ]:
ndim, nwalkers = 3, 10
pos = [result[0] + 1e-3*np.random.randn(1) for i in range(nwalkers)]
pos

In [22]:
pos = []

factorInitialChain = 1e-3

for i in range(nwalkers):
    pos += [result[0] + factorInitialChain*np.random.random_sample(),
            result[1] + factorInitialChain*np.random.random_sample(),
            result[2] + factorInitialChain*np.random.randn()]

In [23]:
pos

[1.0004247347341071,
 0.00010180508708933843,
 3.9983128134077441,
 1.0004522112097063,
 0.00049088860581868426,
 3.9995914410749709,
 1.0009625493830951,
 0.00021701619795770665,
 3.9985444448225693,
 1.0003624636561259,
 0.00045063433485821396,
 4.0004133858630953,
 1.0006687094891336,
 2.1432811720226924e-05,
 4.0005876553753428,
 1.0005060839511526,
 0.00082519017635768091,
 3.9999785497615399,
 1.0003028411503685,
 4.8978361959227325e-05,
 3.9995446671058454,
 1.0009539046028573,
 0.00018554897475091126,
 3.9994330970373655,
 1.0007751774830249,
 0.00045335925671304413,
 4.0001233971180854,
 1.0003601523998311,
 0.00023450490125024581,
 4.0004977475573034]